INVEST_TYPE_NBS = 'NBS'
INVEST_TYPE_BAU = 'BAU'
INVEST_TYPE_CURRENT = 'CURRENT'
INVEST_TYPE_QUALITY = 'QUALITY'

INVEST_QUALITY_DIR = '01-INVEST_QUALITY'
PREPROC_RIOS_DIR = '02-PREPROC_RIOS'
LANDCOVER_DIR = '03-LandCover'
RIOS_DIR = '04-RIOS'
DISAGGREGATION_DIR = "07-DISAGGREGATION"

OUT_ROI_DIR = 'out'
IMPLEMENTATION_ROI_DB = 'Implementación'
MAINTENANCE_ROI_DB = 'Mantenimiento'
OPPORTUNITY_ROI_DB = 'Oportunidad'
TRANSACTION_ROI_DB = 'Transacción'
PLATFORM_ROI_DB = 'Plataforma'
INTAKE_ROI_DB = 'INTAKE'
PTAP_ROI_DB = 'PTAP'
CARBON_ROI_DB = 'CARBONO'


OUT_BASE_DIR = "salidas"
IN_BASE_DIR = "entradas"

ZIP_CREATION_DIR = "https://water-proof.org/outputs/"