INVEST_TYPE_NBS = 'NBS'
INVEST_TYPE_BAU = 'BAU'
INVEST_TYPE_CURRENT = 'CURRENT'
INVEST_TYPE_QUALITY = 'QUALITY'

INVEST_QUALITY_DIR = '01-INVEST_QUALITY'

OUT_ROI_DIR = 'out'
IMPLEMENTATION_ROI_DB = 'Implementación'
MAINTENANCE_ROI_DB = 'Mantenimiento'
OPPORTUNITY_ROI_DB = 'Oportunidad'
TRANSACTION_ROI_DB = 'Transacción'
PLATFORM_ROI_DB = 'Plataforma'
INTAKE_ROI_DB = 'INTAKE'
PTAP_ROI_DB = 'PTAP'
CARBON_ROI_DB = 'CARBONO'

