version: '3'

# volumes:
#   outputs:
#     external: true
#   inputs:
#     external: true

    
services:
  wfapp_py3:
    image: wfapp_py3
    container_name: wfapp_py3_container
    build: .
    environment:
      - PG_HOST=${PG_HOST}
      - PG_GEO_DATABASE=${PG_GEO_DATABASE}
      - PG_GEO_USER=${PG_GEO_USER}
      - PG_GEO_PASSWORD=${PG_GEO_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PATH_FILES=${PATH_FILES}
      - GDAL_DATA=/usr/share/gdal
    volumes:
      - /data/global_datasets/:/home/skaphe/Documentos/tnc/modelos/entradas/
      - /data/outputs/:/home/skaphe/Documentos/tnc/modelos/salidas/
    ports:
      - 8000:8000
      - 3000:3000
    networks:
      - shared-models
      
networks:
  shared-models:
    driver: bridge
