version: '3'

# volumes:
#   outputs:
#     external: true
#   inputs:
#     external: true

    
services:
  wfapp_py3:
    image: wfapp_py3
    container_name: wfapp_py3_container
    build: .
    environment:
      - PG_HOST=${PG_HOST}
      - PG_GEO_DATABASE=${PG_GEO_DATABASE}
      - PG_GEO_USER=${PG_GEO_USER}
      - PG_GEO_PASSWORD=${PG_GEO_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PATH_FILES=${PATH_FILES}
      - GDAL_DATA=/usr/share/gdal
      - ZIP_CREATION_DIR=${ZIP_CREATION_DIR}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - /data/global_datasets/:/home/skaphe/Documentos/tnc/modelos/entradas/
      - /data/outputs/:/home/skaphe/Documentos/tnc/modelos/salidas/      
    ports:
      - 8000:8000
      - 3000:3000
    networks:
      - shared-models

  worker:
    build: .
    command: celery worker --app=worker.celery --loglevel=info
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: .
    command:  flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker

networks:
  shared-models:
    driver: bridge
